export enum ClientPacketType {
  CHAT = 0,
  MOVEMENT = 2,
  ANGLE = 3,
  START_HIT = 4,
  EQUIP = 5,
  DROP_ALL_ITEM = 6,
  CRAFT = 7,
  GIVE_ITEM_CHEST = 8,
  TAKE_ITEM_CHEST = 9,
  PING = 13,
  STOP_HIT = 14,
  UNLOCK_CHEST = 15,
  LOCK_CHEST = 16,
  BUILD = 102,
  RESTORE_CAM = 11,
  BUY_KIT = 21,
  DROP_ONE_ITEM = 28,
  BUY_MARKET = 32,
  JOIN_TEAM = 18,
  KICK_TEAM = 20,
  LEAVE_TEAM = 19,
  LOCK_TEAM = 35,
  CONSOLE_COMMAND = 36,
  TAKE_EXTRACTOR = 37,
  GIVE_WOOD_EXTRACTOR = 38,
  GIVE_FLOUR_OVEN = 24,
  GIVE_WOOD_OVEN = 25,
  TAKE_BREAD_OVEN = 26,
  TAKE_FLOUR = 23,
  GIVE_WHEAT = 22,
  GIVE_FURNACE = 12,
  CANCEL_CRAFT = 31,
  RECYCLE = 29,
  CLAIM_QUEST = 27,
}

export enum ServerPacketTypeJson {
  Chat,
  Kick,
  NewPlayer,
  Handshake,
  AlertMessage,
  ConsoleCommandResponse,
  ServerDescription,
  MessageBeforeJoin,
  LeaderboardUpdate,
  DecreaseItem,
  GatherItem,
  XzKarmani,
  XzKarmani2,
  KillPlayer,
  Muted,
  Throttle,
  RecoverFocus,
  AlertedIssue,
  RecreateSession,
  Verify,
  Minimap,
  Test = 21,
  CHANGE_NAME = 40,
}

export enum ServerPacketTypeBinary {
  EntityUpdate,
  EntityUpdateHardReset,

  CancelCraft,
  Gather,

  OldVersion, // Sent when client tries to join with too old version    I
  ServerIsFull,
  WrongTool, // как назвать типо не той киркой копаешь aka деревянной алмазы

  ResourceHitten,
  BuildStop,
  CraftOk,
  InventoryIsFull,
  InventoryRemoveItem,
  Workbench,
  HittenOther,
  Muted,
  KillPlayer,
  Gauges,
  RecoverFocus,
  ResourceIsEmpty,
  Fire,
  Survive,
  Leaderboard,
  SetWorldTime,
  SetCamera,
  AcceptBuild,
  Killed, // no work
  Minimap,
  RestoreFailed,
  Ghost,
  Resurrected,
  YourTokenIsStolen,
  JoinNewTeam,
  ExcludeTeam,
  NewTeamMember,
  TeamIsDestroyed,
  KitOk,
  Water,

  GaugeLife,
  GaugeFood,
  GaugeWater,

  GetBag,
  VerifiedAccount, // aka set skin & level
  QuestComplete,
  QuestFailed,
  Claimed,
  RecycleOk,
  RecycleStop,
  Well,
  NoResources,
  DecreaseItem2,
  Blocked,
  DeleteInvOk,
  DeleteOneInvOk,
  AccountOk,
  GaugesWarm,
  GaugesCold,
  NewVersion,
  WrongServerPassword,
  CleanInventory,
  HideShopKit,
  ForceCamDelay,
  DeleteSingleInv,
  HideClock,
  HideRecipeBook,
  HideQuestButton,
  HideMarket,
  ExplorerQuest,
  SandTempest,
  Blizzard,
  BlizzardStatus = 70,
  Bandage = 71,
  EntityDelete = 72,
}

// я ща добавлю все
